import { LitElement, TemplateResult } from 'lit';
import { TreeGrid, TreeSelection } from '@openenergytools/tree-grid';
import { OscdOutlinedButton } from '@omicronenergy/oscd-ui/button/OscdOutlinedButton.js';
import { OscdDialog } from '@omicronenergy/oscd-ui/dialog/OscdDialog.js';
import { OscdFab } from '@omicronenergy/oscd-ui/fab/OscdFab.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { OscdCircularProgress } from '@omicronenergy/oscd-ui/progress/OscdCircularProgress.js';
import { OscdOutlinedTextField } from '@omicronenergy/oscd-ui/textfield/OscdOutlinedTextField.js';
import { OscdIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdIconButton.js';
import { OscdAssistChip } from '@omicronenergy/oscd-ui/chips/OscdAssistChip.js';
import { AddDataObjectDialog } from './components/add-data-object-dialog.js';
import { DeleteDialog } from './components/delete-lnodetype-dialog.js';
import { LNodeTypeSidebar } from './components/lnodetype-sidebar.js';
import { SettingsDialog } from './components/settings-dialog.js';
import { EmptyReferencedElement, type MissingMandatoryField } from './foundation/utils.js';
declare const NsdTemplateUpdated_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export default class NsdTemplateUpdated extends NsdTemplateUpdated_base {
    static scopedElements: {
        'tree-grid': typeof TreeGrid;
        'oscd-fab': typeof OscdFab;
        'oscd-icon': typeof OscdIcon;
        'oscd-dialog': typeof OscdDialog;
        'oscd-outlined-button': typeof OscdOutlinedButton;
        'oscd-circular-progress': typeof OscdCircularProgress;
        'oscd-outlined-text-field': typeof OscdOutlinedTextField;
        'oscd-icon-button': typeof OscdIconButton;
        'oscd-assist-chip': typeof OscdAssistChip;
        'add-data-object-dialog': typeof AddDataObjectDialog;
        'delete-dialog': typeof DeleteDialog;
        'lnodetype-sidebar': typeof LNodeTypeSidebar;
        'settings-dialog': typeof SettingsDialog;
    };
    doc?: XMLDocument;
    editCount: number;
    treeUI: TreeGrid;
    warningDialog?: OscdDialog;
    choiceDialog?: OscdDialog;
    deleteDialog: DeleteDialog;
    addDataObjectDialog: HTMLElement & {
        show: () => void;
        validateForm: () => boolean;
    };
    settingsDialog: SettingsDialog;
    lnodeTypeDesc: OscdOutlinedTextField;
    lNodeTypes: Element[];
    selectedLNodeType?: Element;
    lNodeTypeSelection?: TreeSelection;
    nsdSelection?: TreeSelection;
    warningMsg: string;
    loading: boolean;
    fabLabel: string;
    disableAddDataObjectButton: boolean;
    lNodeTypeDescription: string;
    missingMandatoryFields: MissingMandatoryField[];
    emptyReferencedElements: EmptyReferencedElement[];
    missingFieldsCollapsed: boolean;
    private toggleMissingFieldsPanel;
    updated(changedProperties: Map<string, unknown>): void;
    private refreshSelectedLNodeType;
    private cloneSelection;
    private resetUI;
    private openAddDataObjectDialog;
    private showWarning;
    private focusTreePath;
    private getHeaderOffset;
    private warningPathFromEntry;
    private closeWarningDialog;
    private closeChoiceDialog;
    private applyDescriptionUpdate;
    private saveTemplates;
    private showSuccessFeedback;
    private buildUpdateEdits;
    private updateLNodeTypeDescription;
    private proceedWithDataLoss;
    private confirmDelete;
    private handleUpdateTemplate;
    onLNodeTypeSelect(e: CustomEvent): Promise<void>;
    private addDataObjectToTree;
    private handleAddDOConfirm;
    renderWarning(): TemplateResult;
    renderChoice(): TemplateResult;
    renderFab(): TemplateResult;
    renderLNodeTypeControls(): TemplateResult;
    renderMissingMandatoryFields(): TemplateResult;
    render(): TemplateResult<1>;
    static styles: import("lit").CSSResult;
}
export {};
